/*!
 * Reference check of the THM external Coulomb term, ThmCoulombTerm
 * (src/ThmFunc.cpp):
 *
 *   C_l(E) = 2 eta k Int_a^inf dr O_l(k r) / O_l(k a) j_l(p r),
 *
 * O_l = G_l + i F_l for E > 0, W_{-eta, l+1/2}(2 kappa r) for E < 0 and the
 * zero-energy solution sqrt(r) K_{2l+1}(sqrt(8 eta k r)) at E = 0.
 *
 * The expected values come from thm_coulomb_term_reference.py in this
 * directory: mpmath at 25 digits, O_l from mpmath.whitw (not from the library
 * Coulomb functions the engine uses), and the conditionally convergent
 * radial integral evaluated along two rays into the complex r plane starting
 * at the channel radius itself -- no real-axis quadrature and no asymptotic
 * expansion, so it shares no numerics with the C++ implementation.  The script
 * also cross-checks itself against a real-axis + ray split (agreement ~1e-16).
 *
 * The four pairs: 7Li+p and 6Li+d (eta <~ 2 in the grid, the THM light-ion
 * cases), 12C+12C (eta up to 62 at 50 keV, deep sub-barrier), and 17O+n
 * (neutral: must be exactly zero).
 *
 * Run:  tests/reference/thm_coulomb_term_test         (ctest: thm_coulomb_term)
 *       tests/reference/thm_coulomb_term_test -v      (print every value + timing)
 */
#include <algorithm>
#include <chrono>
#include <cmath>
#include <cstdio>
#include <cstring>
#include <iostream>
#include <map>
#include <sstream>
#include <string>

#include "Config.h"
#include "Constants.h"
#include "NucLine.h"
#include "PPair.h"
#include "ThmFunc.h"

// Each consumer of the engine defines this itself (src/AZURE2.cpp for the CLI,
// api/src/pybind_api.cpp for the Python API).  CoulFunc reads it at
// construction; null means no hybrid nuclear potential.
Config *g_config = nullptr;

namespace {

// |got - want| <= kRelTol |want| + kAbsTol.
const double kRelTol = 1.0e-5;
const double kAbsTol = 1.0e-8;

struct PairSpec {
  int z1, z2;
  double m1, m2, a, bindingE;
};

const std::map<std::string, PairSpec> kPairs = {
    {"7Li+p", {3, 1, 7.016003, 1.007276, 4.0, 2.2246}},
    {"6Li+d", {3, 1, 6.015123, 2.014102, 4.5, 1.4735}},
    {"12C+12C", {6, 6, 12.0, 12.0, 6.0, 10.27}},
    {"17O+n", {8, 0, 16.999131, 1.008665, 5.0, 4.143}},
};

struct RefValue {
  const char *pair;
  double E;
  int l;
  double re, im;
};

// clang-format off
const RefValue kReference[] = {
// name, E (MeV), l, Re C, Im C   (generated by thm_coulomb_term_reference.py)
    {"7Li+p", -1.0, 0, 0.38864913587235675, 0.0},
    {"7Li+p", -1.0, 1, 0.2018927011643953, 0.0},
    {"7Li+p", -1.0, 2, 0.051543183247018336, 0.0},
    {"7Li+p", -1.0, 3, 8.4802013999068933e-3, 0.0},
    {"7Li+p", -0.1, 0, 0.28136354629699682, 0.0},
    {"7Li+p", -0.1, 1, 0.24065743499690682, 0.0},
    {"7Li+p", -0.1, 2, 0.085604595783009743, 0.0},
    {"7Li+p", -0.1, 3, 0.018905957195276692, 0.0},
    {"7Li+p", 0.0, 0, 0.26780753530891673, 0.0},
    {"7Li+p", 0.0, 1, 0.24355889229455521, 0.0},
    {"7Li+p", 0.0, 2, 0.089260877825715534, 0.0},
    {"7Li+p", 0.0, 3, 0.020209782679482707, 0.0},
    {"7Li+p", 0.05, 0, 0.26054407535083244, -7.7233059119950443e-6},
    {"7Li+p", 0.05, 1, 0.24495273666843276, 2.5419610028423461e-7},
    {"7Li+p", 0.05, 2, 0.091086396866403818, 6.0510830370514524e-9},
    {"7Li+p", 0.05, 3, 0.020872002531379695, 4.0456377516193473e-11},
    {"7Li+p", 0.3, 0, 0.2205633753059733, -9.0122051443609502e-3},
    {"7Li+p", 0.3, 1, 0.25153198784263598, 5.9863145978531691e-4},
    {"7Li+p", 0.3, 2, 0.1002648794578512, 5.6078857340477281e-5},
    {"7Li+p", 0.3, 3, 0.024289446855430455, 1.6334898920028604e-6},
    {"7Li+p", 1.0, 0, 0.15172526475132814, -0.056174292964552421},
    {"7Li+p", 1.0, 1, 0.25858416540210074, 5.9491431519897485e-3},
    {"7Li+p", 1.0, 2, 0.12564689546839983, 2.5636491020578955e-3},
    {"7Li+p", 1.0, 3, 0.034827912350101295, 2.2783641439256889e-4},
    {"7Li+p", 3.0, 0, 0.04920933108290445, -0.1259486642471762},
    {"7Li+p", 3.0, 1, 0.23070316229777159, -6.7484478618669302e-3},
    {"7Li+p", 3.0, 2, 0.17317099444251832, 0.02179578356969235},
    {"7Li+p", 3.0, 3, 0.068405456079969955, 6.1687668222389209e-3},
    {"7Li+p", 6.0, 0, -0.044730150555104396, -0.15223544409608562},
    {"7Li+p", 6.0, 1, 0.17427055463580504, -0.055239808232617904},
    {"7Li+p", 6.0, 2, 0.18927303539718481, 0.030975051705490541},
    {"7Li+p", 6.0, 3, 0.10884819184481905, 0.024569112032684104},
    {"6Li+d", -1.0, 0, 0.64445421411034593, 0.0},
    {"6Li+d", -1.0, 1, 0.27791216126659269, 0.0},
    {"6Li+d", -1.0, 2, 0.062914327427401306, 0.0},
    {"6Li+d", -1.0, 3, 9.4036079799423431e-3, 0.0},
    {"6Li+d", -0.1, 0, 0.34444346422574328, 0.0},
    {"6Li+d", -0.1, 1, 0.37143991114639814, 0.0},
    {"6Li+d", -0.1, 2, 0.16062597141220863, 0.0},
    {"6Li+d", -0.1, 3, 0.042874595792344129, 0.0},
    {"6Li+d", 0.0, 0, 0.31051607478391655, 0.0},
    {"6Li+d", 0.0, 1, 0.3733019518430072, 0.0},
    {"6Li+d", 0.0, 2, 0.16991007399998177, 0.0},
    {"6Li+d", 0.0, 3, 0.047238158749574772, 0.0},
    {"6Li+d", 0.05, 0, 0.29295642479793566, -1.5151202349570473e-6},
    {"6Li+d", 0.05, 1, 0.37377422175357725, 7.7051195713922724e-9},
    {"6Li+d", 0.05, 2, 0.17445239204654586, 2.3551760395764413e-9},
    {"6Li+d", 0.05, 3, 0.049455323455462045, 3.5735415799037171e-11},
    {"6Li+d", 0.3, 0, 0.19638910689903322, -0.014576980516328432},
    {"6Li+d", 0.3, 1, 0.37155041270233203, -1.1176023707472925e-4},
    {"6Li+d", 0.3, 2, 0.19636614487247975, 1.2211191643032485e-4},
    {"6Li+d", 0.3, 3, 0.060886021792486508, 7.1124891048300281e-6},
    {"6Li+d", 1.0, 0, 0.034739958283549737, -0.11316066673667688},
    {"6Li+d", 1.0, 1, 0.3344403927512458, -0.014174898815240511},
    {"6Li+d", 1.0, 2, 0.24781751670306523, 6.0565653477333928e-3},
    {"6Li+d", 1.0, 3, 0.095548900468890868, 1.1998145231749636e-3},
    {"6Li+d", 3.0, 0, -0.15317981954491111, -0.1847221091300596},
    {"6Li+d", 3.0, 1, 0.19796569675836576, -0.11168596030570363},
    {"6Li+d", 3.0, 2, 0.28496785664564601, 0.01232246084699451},
    {"6Li+d", 3.0, 3, 0.18359222104220977, 0.022481031330199408},
    {"6Li+d", 6.0, 0, -0.25438291024537024, -0.10372575769553438},
    {"6Li+d", 6.0, 1, 0.026235671617965359, -0.19512428962993527},
    {"6Li+d", 6.0, 2, 0.22993065787866563, -0.059123946739437188},
    {"6Li+d", 6.0, 3, 0.23141109482069179, 0.03538272102929672},
    {"12C+12C", -1.0, 0, -0.56674686358737891, 0.0},
    {"12C+12C", -1.0, 1, 0.21904325311950503, 0.0},
    {"12C+12C", -1.0, 2, 0.62761737273200909, 0.0},
    {"12C+12C", -1.0, 3, 0.073089278760217238, 0.0},
    {"12C+12C", -0.1, 0, -0.59920620866144905, 0.0},
    {"12C+12C", -0.1, 1, -0.091978250819772481, 0.0},
    {"12C+12C", -0.1, 2, 0.57466277749141236, 0.0},
    {"12C+12C", -0.1, 3, 0.34596339788690463, 0.0},
    {"12C+12C", 0.0, 0, -0.59323749454972323, 0.0},
    {"12C+12C", 0.0, 1, -0.12408987161538842, 0.0},
    {"12C+12C", 0.0, 2, 0.56037560390127032, 0.0},
    {"12C+12C", 0.0, 3, 0.3703879085108428, 0.0},
    {"12C+12C", 0.05, 0, -0.5895993179670248, 2.9293391173694992e-18},
    {"12C+12C", 0.05, 1, -0.13984552604243618, -4.4503854002351808e-19},
    {"12C+12C", 0.05, 2, 0.55269141321239128, -2.9918554146877554e-18},
    {"12C+12C", 0.05, 3, 0.38209512688447774, -1.068240295046484e-18},
    {"12C+12C", 0.3, 0, -0.5651764829012289, 7.4351053224489528e-18},
    {"12C+12C", 0.3, 1, -0.21525302562181801, -1.0217529789390111e-19},
    {"12C+12C", 0.3, 2, 0.509241441092323, -7.3578434658814363e-18},
    {"12C+12C", 0.3, 3, 0.4354173070287195, -3.5901380176604326e-18},
    {"12C+12C", 1.0, 0, -0.4491062732831452, 1.3419668430696e-17},
    {"12C+12C", 1.0, 1, -0.3897629700344897, 4.3569432414278809e-18},
    {"12C+12C", 1.0, 2, 0.35169037586926241, -1.2065846012669481e-17},
    {"12C+12C", 1.0, 3, 0.53619294086237664, -1.0258817034384819e-17},
    {"12C+12C", 3.0, 0, 0.068160609693620507, 7.6491127626785846e-8},
    {"12C+12C", 3.0, 1, -0.51720119416479683, 4.6770637603927556e-8},
    {"12C+12C", 3.0, 2, -0.18466369042050635, -2.281366487941454e-8},
    {"12C+12C", 3.0, 3, 0.44741999378788299, -1.3366630830189451e-8},
    {"12C+12C", 6.0, 0, 0.47389505060572998, -2.964671555009872e-3},
    {"12C+12C", 6.0, 1, 0.054525615144561887, 7.0229331688776707e-3},
    {"12C+12C", 6.0, 2, -0.46408704009453975, 2.7743942201199672e-3},
    {"12C+12C", 6.0, 3, -0.19926754961386694, -2.031954946029273e-3},
    {"17O+n", -1.0, 0, 0.0, 0.0},
    {"17O+n", -1.0, 1, 0.0, 0.0},
    {"17O+n", -1.0, 2, 0.0, 0.0},
    {"17O+n", -1.0, 3, 0.0, 0.0},
    {"17O+n", -0.1, 0, 0.0, 0.0},
    {"17O+n", -0.1, 1, 0.0, 0.0},
    {"17O+n", -0.1, 2, 0.0, 0.0},
    {"17O+n", -0.1, 3, 0.0, 0.0},
    {"17O+n", 0.0, 0, 0.0, 0.0},
    {"17O+n", 0.0, 1, 0.0, 0.0},
    {"17O+n", 0.0, 2, 0.0, 0.0},
    {"17O+n", 0.0, 3, 0.0, 0.0},
    {"17O+n", 0.05, 0, 0.0, 0.0},
    {"17O+n", 0.05, 1, 0.0, 0.0},
    {"17O+n", 0.05, 2, 0.0, 0.0},
    {"17O+n", 0.05, 3, 0.0, 0.0},
    {"17O+n", 0.3, 0, 0.0, 0.0},
    {"17O+n", 0.3, 1, 0.0, 0.0},
    {"17O+n", 0.3, 2, 0.0, 0.0},
    {"17O+n", 0.3, 3, 0.0, 0.0},
    {"17O+n", 1.0, 0, 0.0, 0.0},
    {"17O+n", 1.0, 1, 0.0, 0.0},
    {"17O+n", 1.0, 2, 0.0, 0.0},
    {"17O+n", 1.0, 3, 0.0, 0.0},
    {"17O+n", 3.0, 0, 0.0, 0.0},
    {"17O+n", 3.0, 1, 0.0, 0.0},
    {"17O+n", 3.0, 2, 0.0, 0.0},
    {"17O+n", 3.0, 3, 0.0, 0.0},
    {"17O+n", 6.0, 0, 0.0, 0.0},
    {"17O+n", 6.0, 1, 0.0, 0.0},
    {"17O+n", 6.0, 2, 0.0, 0.0},
    {"17O+n", 6.0, 3, 0.0, 0.0},
};
// clang-format on

// A PPair built through the same 31(+2)-column NucLine the .azr reader uses.
PPair makePair(const PairSpec &s) {
  std::ostringstream line;
  line.precision(15);  // the default 6 digits would round the masses
  // levelJ pi E fix aa ir s l id active chFix gamma j1 pi1 j2 pi2 e2 m1 m2 z1 z2
  // entSepE sepE j3 pi3 e3 pType chRad g1 g2 ecMask bindingE
  line << "1 1 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 " << s.m1 << " " << s.m2 << " " << s.z1 << " "
       << s.z2 << " 0 0 0 1 0 0 " << s.a << " 0 0 0 " << s.bindingE;
  std::istringstream in(line.str());
  NucLine nl(in);
  return PPair(nl);
}

double halfOffShellMomentum(PPair &pair, double E, double B) {
  return ThmRho(pair.GetRedMass() * uconv, E, B, 1.0);  // fm^-1
}

int failures = 0;
int checks = 0;

void check(const std::string &name, bool ok, const std::string &detail = "") {
  checks++;
  if (!ok) {
    std::cout << "  FAIL  " << name;
    if (!detail.empty()) std::cout << "  -- " << detail;
    std::cout << std::endl;
    failures++;
  }
}

}  // namespace

int main(int argc, char **argv) {
  const bool verbose = argc > 1 && std::strcmp(argv[1], "-v") == 0;
  std::cout << "THM external Coulomb term vs mpmath reference" << std::endl;

  double worstRel = 0.0, worstGsl = 0.0;
  double totalMs = 0.0, maxMs = 0.0;
  int timed = 0;
  for (const RefValue &ref : kReference) {
    const PairSpec &spec = kPairs.at(ref.pair);
    PPair pair = makePair(spec);
    const double p = halfOffShellMomentum(pair, ref.E, spec.bindingE);
    // useGSL must not matter: O_l is not taken from a library routine (GSL's
    // Coulomb functions are off by up to ~2% for l >= 2, eta ~ 2, rho ~ 1-4).
    for (int useGSL = 0; useGSL <= 1; useGSL++) {
      auto t0 = std::chrono::steady_clock::now();
      complex got = ThmCoulombTerm(&pair, ref.l, ref.E, p, useGSL == 1);
      double ms = std::chrono::duration<double, std::milli>(std::chrono::steady_clock::now() - t0).count();
      if (!useGSL) {
        totalMs += ms;
        maxMs = std::max(maxMs, ms);
        timed++;
      }
      const complex want(ref.re, ref.im);
      const double err = std::abs(got - want);
      const double rel = err / std::max(std::abs(want), 1.0e-300);
      if (std::abs(want) > 1.0e-3) {
        if (useGSL)
          worstGsl = std::max(worstGsl, rel);
        else
          worstRel = std::max(worstRel, rel);
      }
      char name[128], detail[256];
      snprintf(name, sizeof(name), "%s E=%g l=%d %s", ref.pair, ref.E, ref.l, useGSL ? "gsl" : "builtin");
      snprintf(detail, sizeof(detail), "got (%.10g, %.10g), want (%.10g, %.10g), rel %.2e",
               got.real(), got.imag(), want.real(), want.imag(), rel);
      if (verbose)
        std::cout << "  " << name << "  " << detail << "  " << ms << " ms" << std::endl;
      check(name, err <= kRelTol * std::abs(want) + kAbsTol, detail);
    }
  }

  // A neutral pair has no Coulomb term: exactly zero, not merely small.
  {
    PPair n = makePair(kPairs.at("17O+n"));
    for (double E : {-1.0, 0.0, 0.3, 3.0}) {
      complex v = ThmCoulombTerm(&n, 1, E, halfOffShellMomentum(n, E, 4.143), false);
      check("17O+n exactly zero", v.real() == 0.0 && v.imag() == 0.0);
    }
  }

  // E < 0 and E = 0 are real (the Whittaker ratio is real).
  {
    PPair lp = makePair(kPairs.at("7Li+p"));
    for (double E : {-0.5, 0.0}) {
      complex v = ThmCoulombTerm(&lp, 0, E, halfOffShellMomentum(lp, E, 2.2246), false);
      check("7Li+p real below threshold", v.imag() == 0.0);
    }
  }

  // Continuity through threshold: both sides approach the E = 0 limit.
  {
    PPair lp = makePair(kPairs.at("7Li+p"));
    const double B = 2.2246;
    complex c0 = ThmCoulombTerm(&lp, 0, 0.0, halfOffShellMomentum(lp, 0.0, B), false);
    for (double E : {-1.0e-4, 1.0e-4}) {
      complex v = ThmCoulombTerm(&lp, 0, E, halfOffShellMomentum(lp, E, B), false);
      char detail[128];
      snprintf(detail, sizeof(detail), "C(%g) = (%.8g, %.8g), C(0) = (%.8g, %.8g)", E, v.real(), v.imag(),
               c0.real(), c0.imag());
      check("threshold continuity", std::abs(v - c0) < 1.0e-3 * std::abs(c0), detail);
    }
  }

  std::cout << "  worst relative error (|C| > 1e-3): built-in " << worstRel << ", GSL " << worstGsl
            << std::endl;
  std::cout << "  time per call: mean " << totalMs / std::max(timed, 1)
            << " ms, max " << maxMs << " ms" << std::endl;
  std::cout << checks - failures << "/" << checks << " checks passed" << std::endl;
  return failures == 0 ? 0 : 1;
}
